# https://github.com/hasura/graphql-engine/tree/stable/install-manifests/docker-compose

version: "3.6"

services:
  # https://github.com/docker-library/docs/blob/master/postgres
  postgres:
    image: postgres:14
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  # https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference
  graphql-engine:
    image: hasura/graphql-engine:v2.6.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      WEBHOOK_URL: http://host.docker.internal:3000

volumes:
  db_data:
