# https://hasura.io/docs/latest/graphql/core/hasura-cli/config-reference

version: 3

endpoint: http://localhost:8080
admin_secret: myadminsecretkey
metadata_directory: .hasura

actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
