//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Eq, PartialEq, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "auction")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub created: DateTime,
  pub updated: Option<DateTime>,
  pub show_id: Uuid,
  pub product_id: Uuid,
  pub started: Option<DateTime>,
  pub expired: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, DeriveRelation, EnumIter)]
pub enum Relation {
  #[sea_orm(has_many = "super::bid::Entity")]
  Bid,
  #[sea_orm(
    belongs_to = "super::product::Entity",
    from = "Column::ProductId",
    to = "super::product::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Product,
  #[sea_orm(
    belongs_to = "super::show::Entity",
    from = "Column::ShowId",
    to = "super::show::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Show,
}

impl Related<super::bid::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Bid.def()
  }
}

impl Related<super::product::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Product.def()
  }
}

impl Related<super::show::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Show.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, DeriveRelatedEntity, EnumIter)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::bid::Entity")]
  Bid,
  #[sea_orm(entity = "super::product::Entity")]
  Product,
  #[sea_orm(entity = "super::show::Entity")]
  Show,
}
