//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Eq, PartialEq, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "bids")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub created: DateTime,
  pub updated: Option<DateTime>,
  pub auction_id: Uuid,
  pub bidder_id: Uuid,
  pub concurrent_amount: Decimal,
  pub amount: Decimal,
}

#[derive(Copy, Clone, Debug, DeriveRelation, EnumIter)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::auction::Entity",
    from = "Column::AuctionId",
    to = "super::auction::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Auction,
  #[sea_orm(
    belongs_to = "super::person::Entity",
    from = "Column::BidderId",
    to = "super::person::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Person,
}

impl Related<super::auction::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Auction.def()
  }
}

impl Related<super::person::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Person.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, DeriveRelatedEntity, EnumIter)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::auction::Entity")]
  Auction,
  #[sea_orm(entity = "super::person::Entity")]
  Person,
}
