//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Eq, PartialEq, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub created: DateTime,
  pub updated: Option<DateTime>,
  #[sea_orm(column_type = "Text")]
  pub name: String,
}

#[derive(Copy, Clone, Debug, DeriveRelation, EnumIter)]
pub enum Relation {
  #[sea_orm(has_many = "super::auction::Entity")]
  Auction,
}

impl Related<super::auction::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Auction.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, DeriveRelatedEntity, EnumIter)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::auction::Entity")]
  Auction,
}
