[package]
name = "bits-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "6.0.7"
bits-data = { path = "../data" }
bits-ops = { path = "../ops" }
bits-core = { path = "../core" }
futures-util = "0.3.0"
