[package]
name = "bits-graphql"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = { workspace = true }
bits-core = { path = "../core" }
graphql_client = "0.13.0"
serde =  { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
dotenv = "0.15.0"
insta = { version = "1.34.0", features = ["json", "redactions"] }
lazy_static = "1.4.0"
