[package]
name = "bits-graphql"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = { version = "6.0.7", features = ["chrono", "decimal", "uuid", "dataloader", "dynamic-schema"] }
bits-core = { path = "../core" }
futures-util = "0.3.0"
lazy_static = { version = "1.4.0" }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }

[dependencies.seaography]
git = "https://github.com/SeaQL/seaography"
rev = "9c43f72"
features = ["with-chrono", "with-decimal", "with-uuid"]
