//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
  fn table_name(&self) -> &str {
    "comment"
  }
}

#[derive(
  Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize,
)]
pub struct Model {
  pub id: Uuid,
  pub created: Option<DateTimeWithTimeZone>,
  pub updated: Option<DateTimeWithTimeZone>,
  pub author_id: Uuid,
  pub show_id: Uuid,
  pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
  Id,
  Created,
  Updated,
  AuthorId,
  ShowId,
  Text,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
  Id,
}

impl PrimaryKeyTrait for PrimaryKey {
  type ValueType = Uuid;
  fn auto_increment() -> bool {
    false
  }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
  Person,
  Show,
}

impl ColumnTrait for Column {
  type EntityName = Entity;
  fn def(&self) -> ColumnDef {
    match self {
      Self::Id => ColumnType::Uuid.def(),
      Self::Created => ColumnType::TimestampWithTimeZone.def(),
      Self::Updated => ColumnType::TimestampWithTimeZone.def().null(),
      Self::AuthorId => ColumnType::Uuid.def(),
      Self::ShowId => ColumnType::Uuid.def(),
      Self::Text => ColumnType::Text.def(),
    }
  }
}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    match self {
      Self::Person => Entity::belongs_to(super::person::Entity)
        .from(Column::AuthorId)
        .to(super::person::Column::Id)
        .into(),
      Self::Show => Entity::belongs_to(super::show::Entity)
        .from(Column::ShowId)
        .to(super::show::Column::Id)
        .into(),
    }
  }
}

impl Related<super::person::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Person.def()
  }
}

impl Related<super::show::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Show.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::person::Entity")]
  Person,
  #[sea_orm(entity = "super::show::Entity")]
  Show,
}
