[package]
name = "bits"
version = "0.1.0"
edition = "2021"
default-run = "bits"

[dependencies]
async-graphql = "6.0.7"
async-graphql-axum = "6.0.7"
axum = { version = "0.6.20", features = ["ws", "headers"] }
bits-graphql = { path = "../graphql" }
dotenv = "0.15.0"
http = "0.2.9"
hyper = "0.14.27"
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
