[package]
name = "bits"
version = "0.1.0"
edition = "2021"
default-run = "bits"

[dependencies]
askama = "0.12.1"
async-graphql-poem = "6.0.10"
bits-graphql = { path = "../graphql" }
dotenv = "0.15.0"
graphql_client = "0.13.0"
http = "0.2.9"
hyper = "0.14.27"
poem = "1.3.58"
rust-i18n = "2.2.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
