# https://doc.rust-lang.org/cargo/reference/config.html

[alias]
dev = "watch --clear --exec run"
lint = "clippy"
snap = "insta review"
task = "run --bin tasks --quiet --release --"

[build]
target-dir = ".build"
