[package]
name = "bits-core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = "6.0.7"
bits-data = { path = "../data" }
futures = "0.3.1"
jsonwebtoken = "9.1.0"
sea-orm = { version = "0.12.0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "seaography"] }
serde = "1.0.188"
serde_json = "1.0.107"
sqlx = "0.7.2"
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
