[package]
name = "bits-core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = "6.0.7"
bits-data = { path = "../data" }
jsonwebtoken = "9.1.0"
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = "0.7.2"
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
insta = { version = "1.34.0", features = ["json", "redactions"] }
