[package]
name = "bits-core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = "6.0.7"
bits-data = { path = "../data" }
futures = "0.3.1"
serde = "1.0.188"
serde_json = "1.0.107"
sqlx = "0.7.2"
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
