type Auction {
  id: String!
  created: String!
  updated: String
  showId: String!
  productId: String!
  startedAt: String
  bid(filters: BidFilterInput, orderBy: BidOrderInput, pagination: PaginationInput): BidConnection!
  product: Product
  show: Show
}

type AuctionConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Auction!]!
  edges: [AuctionEdge!]!
}

type AuctionEdge {
  cursor: String!
  node: Auction!
}

input AuctionFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  updated: TextFilterInput
  showId: TextFilterInput
  productId: TextFilterInput
  startedAt: TextFilterInput
  and: [AuctionFilterInput!]
  or: [AuctionFilterInput!]
}

input AuctionOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  updated: OrderByEnum
  showId: OrderByEnum
  productId: OrderByEnum
  startedAt: OrderByEnum
}

type Bid {
  id: String!
  created: String!
  auctionId: String!
  buyerId: String!
  concurrentAmount: String!
  amount: String!
  auction: Auction
  person: Person
}

type BidConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Bid!]!
  edges: [BidEdge!]!
}

type BidEdge {
  cursor: String!
  node: Bid!
}

input BidFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  auctionId: TextFilterInput
  buyerId: TextFilterInput
  concurrentAmount: TextFilterInput
  amount: TextFilterInput
  and: [BidFilterInput!]
  or: [BidFilterInput!]
}

input BidInput {
  auctionId: ID!
  buyerId: ID!
  amount: Int!
}

input BidOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  auctionId: OrderByEnum
  buyerId: OrderByEnum
  concurrentAmount: OrderByEnum
  amount: OrderByEnum
}

type BidResult {
  bid: Bid!
}

input BooleanFilterInput {
  eq: Boolean
  ne: Boolean
  gt: Boolean
  gte: Boolean
  lt: Boolean
  lte: Boolean
  is_in: [Boolean!]
  is_not_in: [Boolean!]
  is_null: Boolean
  is_not_null: Boolean
}

type Comment {
  id: String!
  created: String!
  updated: String
  authorId: String!
  showId: String!
  text: String!
  person: Person
  show: Show
}

type CommentConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Comment!]!
  edges: [CommentEdge!]!
}

type CommentEdge {
  cursor: String!
  node: Comment!
}

input CommentFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  updated: TextFilterInput
  authorId: TextFilterInput
  showId: TextFilterInput
  text: StringFilterInput
  and: [CommentFilterInput!]
  or: [CommentFilterInput!]
}

input CommentInput {
  authorId: ID!
  showId: ID!
  text: String!
}

input CommentOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  updated: OrderByEnum
  authorId: OrderByEnum
  showId: OrderByEnum
  text: OrderByEnum
}

type CommentResult {
  comment: Comment!
}

input CreateAuctionInput {
  showId: ID!
  productId: ID!
}

type CreateAuctionResult {
  auction: Auction!
}

input CreateProductInput {
  creatorId: ID!
  name: String!
}

type CreateProductResult {
  product: Product!
}

input CreateShowInput {
  creatorId: ID!
  name: String!
}

type CreateShowResult {
  show: Show!
}

input CursorInput {
  cursor: String
  limit: Int!
}

type Mutation {
  _ping: String
  bid(input: BidInput!): BidResult!
  comment(input: CommentInput!): CommentResult!
  createAuction(input: CreateAuctionInput!): CreateAuctionResult!
  createProduct(input: CreateProductInput!): CreateProductResult!
  createShow(input: CreateShowInput!): CreateShowResult!
  start(input: StartInput!): StartResult!
}

input OffsetInput {
  limit: Int!
  offset: Int!
}

enum OrderByEnum {
  ASC
  DESC
}

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: String
  endCursor: String
}

input PageInput {
  limit: Int!
  page: Int!
}

type PaginationInfo {
  pages: Int!
  current: Int!
  offset: Int!
  total: Int!
}

input PaginationInput {
  cursor: CursorInput
  page: PageInput
  offset: OffsetInput
}

type Person {
  id: String!
  created: String!
  updated: String
  email: String!
  bid(filters: BidFilterInput, orderBy: BidOrderInput, pagination: PaginationInput): BidConnection!
  comment(filters: CommentFilterInput, orderBy: CommentOrderInput, pagination: PaginationInput): CommentConnection!
  product(filters: ProductFilterInput, orderBy: ProductOrderInput, pagination: PaginationInput): ProductConnection!
  show(filters: ShowFilterInput, orderBy: ShowOrderInput, pagination: PaginationInput): ShowConnection!
}

type PersonConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Person!]!
  edges: [PersonEdge!]!
}

type PersonEdge {
  cursor: String!
  node: Person!
}

input PersonFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  updated: TextFilterInput
  email: StringFilterInput
  and: [PersonFilterInput!]
  or: [PersonFilterInput!]
}

input PersonOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  updated: OrderByEnum
  email: OrderByEnum
}

type Product {
  id: String!
  created: String!
  updated: String
  creatorId: String!
  name: String!
  auction(filters: AuctionFilterInput, orderBy: AuctionOrderInput, pagination: PaginationInput): AuctionConnection!
  person: Person
}

type ProductConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Product!]!
  edges: [ProductEdge!]!
}

type ProductEdge {
  cursor: String!
  node: Product!
}

input ProductFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  updated: TextFilterInput
  creatorId: TextFilterInput
  name: StringFilterInput
  and: [ProductFilterInput!]
  or: [ProductFilterInput!]
}

input ProductOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  updated: OrderByEnum
  creatorId: OrderByEnum
  name: OrderByEnum
}

type Query {
  auctions(filters: AuctionFilterInput, orderBy: AuctionOrderInput, pagination: PaginationInput): AuctionConnection!
  bids(filters: BidFilterInput, orderBy: BidOrderInput, pagination: PaginationInput): BidConnection!
  comments(filters: CommentFilterInput, orderBy: CommentOrderInput, pagination: PaginationInput): CommentConnection!
  persons(filters: PersonFilterInput, orderBy: PersonOrderInput, pagination: PaginationInput): PersonConnection!
  products(filters: ProductFilterInput, orderBy: ProductOrderInput, pagination: PaginationInput): ProductConnection!
  shows(filters: ShowFilterInput, orderBy: ShowOrderInput, pagination: PaginationInput): ShowConnection!
}

type Show {
  id: String!
  created: String!
  updated: String
  creatorId: String!
  name: String!
  startedAt: String
  started: Boolean!
  auction(filters: AuctionFilterInput, orderBy: AuctionOrderInput, pagination: PaginationInput): AuctionConnection!
  comment(filters: CommentFilterInput, orderBy: CommentOrderInput, pagination: PaginationInput): CommentConnection!
  person: Person
}

type ShowConnection {
  pageInfo: PageInfo!
  paginationInfo: PaginationInfo
  nodes: [Show!]!
  edges: [ShowEdge!]!
}

type ShowEdge {
  cursor: String!
  node: Show!
}

input ShowFilterInput {
  id: TextFilterInput
  created: TextFilterInput
  updated: TextFilterInput
  creatorId: TextFilterInput
  name: StringFilterInput
  startedAt: TextFilterInput
  started: BooleanFilterInput
  and: [ShowFilterInput!]
  or: [ShowFilterInput!]
}

input ShowOrderInput {
  id: OrderByEnum
  created: OrderByEnum
  updated: OrderByEnum
  creatorId: OrderByEnum
  name: OrderByEnum
  startedAt: OrderByEnum
  started: OrderByEnum
}

input StartInput {
  auctionId: ID!
}

type StartResult {
  auction: Auction!
}

input StringFilterInput {
  eq: String
  ne: String
  gt: String
  gte: String
  lt: String
  lte: String
  is_in: [String!]
  is_not_in: [String!]
  is_null: String
  is_not_null: String
  contains: String
  starts_with: String
  ends_with: String
  like: String
  not_like: String
  between: [String!]
  not_between: [String!]
}

input TextFilterInput {
  eq: String
  ne: String
  gt: String
  gte: String
  lt: String
  lte: String
  is_in: [String!]
  is_not_in: [String!]
  is_null: String
  is_not_null: String
  between: [String!]
  not_between: [String!]
}

